cc_test(
    name = "test-board",
    size = "small",
    srcs = ["test_board.cpp"],
    deps = [
        "//lib:board-lib",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
