// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: tictactoe.proto
#ifndef GRPC_tictactoe_2eproto__INCLUDED
#define GRPC_tictactoe_2eproto__INCLUDED

#include "tictactoe.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace tictactoe {

// The TicTacToe service definition.
class TicTacToe final {
 public:
  static constexpr char const* service_full_name() {
    return "tictactoe.TicTacToe";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Player enters the game
    virtual ::grpc::Status EnterGame(::grpc::ClientContext* context, const ::tictactoe::EnterRequest& request, ::tictactoe::EnterReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tictactoe::EnterReply>> AsyncEnterGame(::grpc::ClientContext* context, const ::tictactoe::EnterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tictactoe::EnterReply>>(AsyncEnterGameRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tictactoe::EnterReply>> PrepareAsyncEnterGame(::grpc::ClientContext* context, const ::tictactoe::EnterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tictactoe::EnterReply>>(PrepareAsyncEnterGameRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Player enters the game
      virtual void EnterGame(::grpc::ClientContext* context, const ::tictactoe::EnterRequest* request, ::tictactoe::EnterReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void EnterGame(::grpc::ClientContext* context, const ::tictactoe::EnterRequest* request, ::tictactoe::EnterReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tictactoe::EnterReply>* AsyncEnterGameRaw(::grpc::ClientContext* context, const ::tictactoe::EnterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tictactoe::EnterReply>* PrepareAsyncEnterGameRaw(::grpc::ClientContext* context, const ::tictactoe::EnterRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status EnterGame(::grpc::ClientContext* context, const ::tictactoe::EnterRequest& request, ::tictactoe::EnterReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tictactoe::EnterReply>> AsyncEnterGame(::grpc::ClientContext* context, const ::tictactoe::EnterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tictactoe::EnterReply>>(AsyncEnterGameRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tictactoe::EnterReply>> PrepareAsyncEnterGame(::grpc::ClientContext* context, const ::tictactoe::EnterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tictactoe::EnterReply>>(PrepareAsyncEnterGameRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void EnterGame(::grpc::ClientContext* context, const ::tictactoe::EnterRequest* request, ::tictactoe::EnterReply* response, std::function<void(::grpc::Status)>) override;
      void EnterGame(::grpc::ClientContext* context, const ::tictactoe::EnterRequest* request, ::tictactoe::EnterReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::tictactoe::EnterReply>* AsyncEnterGameRaw(::grpc::ClientContext* context, const ::tictactoe::EnterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::tictactoe::EnterReply>* PrepareAsyncEnterGameRaw(::grpc::ClientContext* context, const ::tictactoe::EnterRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_EnterGame_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Player enters the game
    virtual ::grpc::Status EnterGame(::grpc::ServerContext* context, const ::tictactoe::EnterRequest* request, ::tictactoe::EnterReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_EnterGame : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_EnterGame() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_EnterGame() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnterGame(::grpc::ServerContext* /*context*/, const ::tictactoe::EnterRequest* /*request*/, ::tictactoe::EnterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEnterGame(::grpc::ServerContext* context, ::tictactoe::EnterRequest* request, ::grpc::ServerAsyncResponseWriter< ::tictactoe::EnterReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_EnterGame<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_EnterGame : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_EnterGame() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::tictactoe::EnterRequest, ::tictactoe::EnterReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::tictactoe::EnterRequest* request, ::tictactoe::EnterReply* response) { return this->EnterGame(context, request, response); }));}
    void SetMessageAllocatorFor_EnterGame(
        ::grpc::MessageAllocator< ::tictactoe::EnterRequest, ::tictactoe::EnterReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::tictactoe::EnterRequest, ::tictactoe::EnterReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_EnterGame() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnterGame(::grpc::ServerContext* /*context*/, const ::tictactoe::EnterRequest* /*request*/, ::tictactoe::EnterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* EnterGame(
      ::grpc::CallbackServerContext* /*context*/, const ::tictactoe::EnterRequest* /*request*/, ::tictactoe::EnterReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_EnterGame<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_EnterGame : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_EnterGame() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_EnterGame() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnterGame(::grpc::ServerContext* /*context*/, const ::tictactoe::EnterRequest* /*request*/, ::tictactoe::EnterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_EnterGame : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_EnterGame() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_EnterGame() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnterGame(::grpc::ServerContext* /*context*/, const ::tictactoe::EnterRequest* /*request*/, ::tictactoe::EnterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEnterGame(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_EnterGame : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_EnterGame() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->EnterGame(context, request, response); }));
    }
    ~WithRawCallbackMethod_EnterGame() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnterGame(::grpc::ServerContext* /*context*/, const ::tictactoe::EnterRequest* /*request*/, ::tictactoe::EnterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* EnterGame(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_EnterGame : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_EnterGame() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::tictactoe::EnterRequest, ::tictactoe::EnterReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::tictactoe::EnterRequest, ::tictactoe::EnterReply>* streamer) {
                       return this->StreamedEnterGame(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_EnterGame() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status EnterGame(::grpc::ServerContext* /*context*/, const ::tictactoe::EnterRequest* /*request*/, ::tictactoe::EnterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedEnterGame(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::tictactoe::EnterRequest,::tictactoe::EnterReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_EnterGame<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_EnterGame<Service > StreamedService;
};

}  // namespace tictactoe


#endif  // GRPC_tictactoe_2eproto__INCLUDED
