// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: tictactoe.proto

#include "tictactoe.pb.h"
#include "tictactoe.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace tictactoe {

static const char* TicTacToe_method_names[] = {
  "/tictactoe.TicTacToe/EnterGame",
};

std::unique_ptr< TicTacToe::Stub> TicTacToe::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TicTacToe::Stub> stub(new TicTacToe::Stub(channel, options));
  return stub;
}

TicTacToe::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_EnterGame_(TicTacToe_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TicTacToe::Stub::EnterGame(::grpc::ClientContext* context, const ::tictactoe::EnterRequest& request, ::tictactoe::EnterReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::tictactoe::EnterRequest, ::tictactoe::EnterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_EnterGame_, context, request, response);
}

void TicTacToe::Stub::async::EnterGame(::grpc::ClientContext* context, const ::tictactoe::EnterRequest* request, ::tictactoe::EnterReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::tictactoe::EnterRequest, ::tictactoe::EnterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EnterGame_, context, request, response, std::move(f));
}

void TicTacToe::Stub::async::EnterGame(::grpc::ClientContext* context, const ::tictactoe::EnterRequest* request, ::tictactoe::EnterReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EnterGame_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::tictactoe::EnterReply>* TicTacToe::Stub::PrepareAsyncEnterGameRaw(::grpc::ClientContext* context, const ::tictactoe::EnterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::tictactoe::EnterReply, ::tictactoe::EnterRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_EnterGame_, context, request);
}

::grpc::ClientAsyncResponseReader< ::tictactoe::EnterReply>* TicTacToe::Stub::AsyncEnterGameRaw(::grpc::ClientContext* context, const ::tictactoe::EnterRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEnterGameRaw(context, request, cq);
  result->StartCall();
  return result;
}

TicTacToe::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TicTacToe_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TicTacToe::Service, ::tictactoe::EnterRequest, ::tictactoe::EnterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TicTacToe::Service* service,
             ::grpc::ServerContext* ctx,
             const ::tictactoe::EnterRequest* req,
             ::tictactoe::EnterReply* resp) {
               return service->EnterGame(ctx, req, resp);
             }, this)));
}

TicTacToe::Service::~Service() {
}

::grpc::Status TicTacToe::Service::EnterGame(::grpc::ServerContext* context, const ::tictactoe::EnterRequest* request, ::tictactoe::EnterReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace tictactoe

