name: build-test

on: push

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.12.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      # - run: bazel build //lib:all
      - run: bazel build //tests:all
      - run: bazel build //bin:all
      
  test: 
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.12.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      - run: bazel test --test_output=all //tests:test-board

  # deploy:
  #   needs: test

  #   permissions:
  #     contents: write
  #     pages: write
  #     id-token: write

  #   environment:
  #     name: production
  #     url: ${{ steps.deployment.outputs.page_url }}

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: checkout repo
  #       uses: actions/checkout@v4
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #     - name: use node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20.x'
  #     - name: configure github pages
  #       uses: actions/configure-pages@v4
  #       with:
  #         static_site_generator: next
  #     - run: npm install
  #     - run: npm run build
  #     - name: upload artifacts
  #       uses: actions/upload-pages-artifact@v3
  #       with:
  #         path: './out'
  #     - name: deploy
  #       id: deployment
  #       uses: actions/deploy-pages@v4
        
      
