name: build-test

on: push

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel build //lib:all
      - run: bazel build //tests:all
      
  # test: 
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: checkout repo
  #       uses: actions/checkout@v4
  #     - uses: bazelbuild/setup-bazelisk@v3
  #     - name: Mount bazel cache  # Optional
  #       uses: actions/cache@v4
  #       with:
  #         path: "~/.cache/bazel"
  #         key: bazel
  #     - run: bazel test //tests:test-board

  # deploy:
  #   needs: test

  #   permissions:
  #     contents: write
  #     pages: write
  #     id-token: write

  #   environment:
  #     name: production
  #     url: ${{ steps.deployment.outputs.page_url }}

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: checkout repo
  #       uses: actions/checkout@v4
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #     - name: use node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20.x'
  #     - name: configure github pages
  #       uses: actions/configure-pages@v4
  #       with:
  #         static_site_generator: next
  #     - run: npm install
  #     - run: npm run build
  #     - name: upload artifacts
  #       uses: actions/upload-pages-artifact@v3
  #       with:
  #         path: './out'
  #     - name: deploy
  #       id: deployment
  #       uses: actions/deploy-pages@v4
        
      
